### ISSUE TITLE
Cosign technical debt

### ISSUE THREAD

**Issue by mtrmac** [containers/image#1601]
Captured from PRs

- [ ] Unit tests for #1595 , at least the config file handling
- [ ] Unit tests for #1597
- [ ] Integration tests for #1595
- [ ] Integration tests for #1597
- [ ] Integration tests for #1598
- [ ] Only fetch the attachment config if we actually have a new signature to add (and if we continue to update the DiffID list).
- [ ] Only upload an updated attachment config and manifest if we added at least one new signature.
- [ ] Consider accepting any of a set of public keys
- [ ] Possibly test `isManifestUnknown` from #1595 against various registries?
- [ ] Possibly consider accepting an image with a signed manifest list but not the individual images (i.e. `cosign sign` without `--recursive`)

**Comment by mtrmac** [comment]
I have moved the Skopeo-specific items to https://github.com/containers/skopeo/issues/1704 .

**Comment by mtrmac** [comment]
https://github.com/letsencrypt/boulder/pull/6651 decreases Skopeo binary size on macOS by 295 kB.
