### ISSUE TITLE
Zstd(:chunked) work tracking checklist

### ISSUE THREAD

**Issue by mtrmac** [containers/image#2189]
- Zstd in general:
  - [ ] Pushes with Zstd compression prefer using schema1 manifests: https://github.com/containers/image/issues/2181
  - [ ] Uncompressed pushes of originally-compressed layers don’t correctly update MIME types (always a bug, but now breaks pushes of originally-Zstd to `docker-archive:` destinations): https://github.com/containers/image/issues/2182
  - [x] Not a bug: pull of gzip + push of zstd changes image ID due to triggering a conversion to OCI: https://github.com/containers/podman/issues/20611
- Zstd:chunked:
  - [ ] Pushes of chunked layers fail because the `UncompressedDigest` fields stores a TOC digest, and layer digest validation fails: Part of https://github.com/containers/image/pull/1980
  - [ ] Pushes reusing chunked layers don’t create the required annotations, making the layers impossible to pull chunked: https://github.com/containers/image/pull/2183#pullrequestreview-1725228215 / https://github.com/containers/image/pull/2185
  - [ ] Pulls of chunked layers do not reuse locally-existing layers: Part of https://github.com/containers/image/pull/1980
  - [ ] Pulls of chunked layers do not reuse locally-existing layers: Part of https://github.com/containers/image/pull/1980
  - [ ] In c/storage, we don’t sufficiently differentiate layers pulled by blob digest vs. TOC digest, and reuse is unclear: Part of https://github.com/containers/image/pull/1980 , and https://github.com/containers/storage/pull/1627#discussion_r1309255199
  - [ ] Pulls may reuse layers pulled by blob digests vs. TOC digests: Part of https://github.com/containers/image/pull/1980
  - [ ] Image deduplication contains a (required!) sanity check that `TopLayer` matches, but that might not be true if layers pulled by blob vs. TOC digests have different IDs: Part of https://github.com/containers/image/pull/1980
  - [ ] At a higher level, it’s unclear how to safely handle signed chunked images: what if the two versions don’t represent exactly the same filesystem?
  - [ ] `blobPipelineDetectCompressionStep` cannot detect zstd:chunked, causing unnecessary recompression: around https://github.com/containers/image/pull/1980#discussion_r1388492171 . (OTOH we can only use :chunked if it comes with the expected annotations.)
  - [ ] `blobPipelineCompressionStep` triggers a recompression of zstd:chunked if the user asks for zstd: around https://github.com/containers/image/pull/1980#discussion_r1388493306
  - [ ] Chunked layers are visible in c/storage, and usable by other processes, while they are still being populated: https://github.com/containers/image/issues/1979
  - [ ] Copies of chunked layers don’t mark the image as requiring Zstd support: https://github.com/containers/image/issues/2077
  - [ ] @mtrmac : Revisit https://github.com/containers/storage/pull/1627#pullrequestreview-1600645581, see where we are

**Comment by giuseppe** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
Should 
```
Pushes reusing chunked layers don’t create the required annotations, making the layers impossible to pull chunked: https://github.com/containers/image/pull/2183#pullrequestreview-1725228215 / https://github.com/containers/image/pull/2185
```
Be closed?

**Comment by cgwalters** [comment]
For the record I think it was me that recently added a [zstd:chunked label](https://github.com/containers/storage/labels/area%2Fzstd%3Achunked) - there's some more stuff there. In particular it seems like https://github.com/containers/storage/issues/1928 is somewhat close to a blocker for wide scale deployment.
